; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppPublisher "ChemBrows"
#define MyAppURL "http://www.chembrows.com/"
#define MyAppExeName "ChemBrows.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A73169C6-5BEB-4A45-AA81-85EF09755349}
AppName={#AppName}
AppVersion={#Version}
;AppVerName={#AppName} {#AppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#AppName}
DefaultGroupName={#AppName}
OutputDir=C:\Users\djipey\Desktop
OutputBaseFilename={#OutputBaseFilename}
Compression=lzma
SolidCompression=yes
SetupIconFile=../images/icon.ico
LicenseFile=../LICENSE.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]

Source: "C:\Users\djipey\Desktop\ChemBrows\pyu-data\deploy\{#AppName}-win-{#Version}\ChemBrows.exe"; DestDir: "{app}"; Flags: ignoreversion

; Put the icon in the app folder, will be used for the desktop icon
Source: "C:\Users\djipey\Desktop\ChemBrows\images\icon.ico"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon
Name: "{group}\{cm:ProgramOnTheWeb,{#AppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#AppName}}; Flags: nowait postinstall skipifsilent
