; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppPublisher "ChemBrows"
#define MyAppURL "http://www.chembrows.com/"
#define MyAppExeName "gui.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A73169C6-5BEB-4A45-AA81-85EF09755349}
AppName={#AppName}
AppVersion={#Version}
;AppVerName={#AppName} {#AppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#AppName}
DefaultGroupName={#AppName}
OutputDir=C:\Users\djipey\Desktop
OutputBaseFilename={#OutputBaseFilename}
Compression=lzma
SolidCompression=yes
SetupIconFile=images/icon.ico
LicenseFile=LICENSE.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\ChemBrows-0.7.0.win32\gui.exe"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\ChemBrows-0.7.0.win32\python34.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\ChemBrows-0.7.0.win32\ChemBrows-0.7.0.win32\*"; DestDir: "{app}\ChemBrows-0.7.0.win32"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\{#AppName}-{#Version}.{#Architecture}\gui.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\{#AppName}-{#Version}.{#Architecture}\python*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\{#AppName}-{#Version}.{#Architecture}\{#AppName}-{#Version}.{#Architecture}\*"; DestDir: "{app}\{#AppName}-{#Version}.{#Architecture}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppName}-{#Version}.{#Architecture}\{#MyAppExeName}"; IconFilename: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\{#AppName}-{#Version}.{#Architecture}\{#AppName}-{#Version}.{#Architecture}\images\icon.ico"
Name: "{group}\{cm:ProgramOnTheWeb,{#AppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\{#AppName}-{#Version}.{#Architecture}\{#MyAppExeName}"; IconFilename: "C:\Users\djipey\Desktop\ChemBrows_freeze\dist\{#AppName}-{#Version}.{#Architecture}\{#AppName}-{#Version}.{#Architecture}\images\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppName}-{#Version}.{#Architecture}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

